* General Notes
** Kexts
Kexts should be installed in =/Library/Extensions=.

Installation:
#+BEGIN_SRC sh
  sudo cp -r <mydriver.kext> /Library/Extensions
  sudo kextcache -i / # update kext cache
#+END_SRC

Common problems are wrong permissions or file ownership.
*Be sure to check output for errors!*
** [[https://github.com/acidanthera/Lilu][Lilu]] [[file:kexts/Lilu.kext][kext]]: Used to patch and process other kexts
** [[https://github.com/RehabMan/OS-X-ACPI-Debug][OS-X-ACPI-Debug]]: "Enable debug tracing from ACPI code (DSDT) to system.log"
Not currently installed, but should be useful for debugging ACPI issues.
* Hardware
** Intel UHD 630 Graphics
Intel graphics is supported by [[https://www.tonymacx86.com/threads/solved-uhd-630-either-not-booting-or-no-acceleration-on-dell-xps-15-9570-4k.261101/page-7#post-1821091][setting active display lanes to 4]].
See [[https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-kernel-panic-due-to-divide-by-zero.261687/][deprecated fix]] by Austere.J - waiting for new patch (TBD).

Some threads discuss setting DVMT pre-alloc in the BIOS, which is not possible on most laptops,
including the XPS 9570. However, the default of 64MB DVMT is sufficient, so fortunately nothing
needs to be done here.

To determine if Intel GPU acceleration is working, check: =About This Mac -> Intel UHD Graphics 630
1536 MB=. A value less than 1536MB indicates a problem (e.g. 7MB or 31MB are common).
*** Enabling acceleration
- [[file:CLOVER/config.plist][config.plist]] changes (enable patch for 10.14 or 10.14.1, as needed)
  - Graphics/Inject/Intel=yes
  - Graphics/ig-platform-id=0x3e9b0000
  - KernelAndKextPatches/KextsToPatch/Item 1 (4 lanes - default for 4K XPS 9570)
  - KernelAndKextPatches/KextsToPatch/Item 2 (2 lanes - disabled by default)
- Install [[https://github.com/PMheart/CoreDisplayFixup][CoreDisplayFixup]] [[file:kexts/CoreDisplayFixup.kext][kext]]
  CoreDisplayFixup is now included in [[https://github.com/acidanthera/WhateverGreen][WhateverGreen]], but the UHD 630 patches are still a work in
  progress, so we'll use CoreDisplayFixup for now.
*** Enabling backlight control via slider in =Sys Prefs -> Displays=
Patched via kext and SSDT patch ([[https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightfixup-kext.218222/][discussion]]).  Can use pre-built [[https://bitbucket.org/RehabMan/applebacklightfixup/downloads/][kext and SSDT-PNLF.aml]], but the
 .aml file should be the same as [[https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PNLF.dsl][SSDT-PNLF.dsl]] from [[https://github.com/RehabMan/OS-X-Clover-Laptop-Config][OS-X-Clover-Laptop-Config]].
- Include [[https://github.com/RehabMan/AppleBacklightFixup][AppleBacklightFixup]] [[file:kexts/AppleBacklightFixup.kext][kext]]
- Include [[file:CLOVER/ACPI/patched/SSDT-PNLF.aml][SSDT-PNLF.aml]] ([[file:CLOVER/ACPI/patched/SSDT-PNLF.dsl][SSDT-PNLF.dsl]])
*** Known issue: [[https://www.tonymacx86.com/threads/bug-black-screen-3-minutes-after-booting-coffeelake-uhd-630.261131/][Black/dark screen 3 minutes after booting with CoffeeLake UHD 630]]
Workaround: wait 3 minutes until a proper solution is found (TBD).

This problem seems to be surpringly difficult to fix, partly because the people who are likely to
find a solution do not yet have UHD 630 hardware.
** Battery Status
- Install [[https://github.com/RehabMan/OS-X-ACPI-Battery-Driver][ACPIBatteryManager]] [[file:kexts/ACPIBatteryManager.kext][kext]]

Only the ACPIBatteryManager kext is reuqired on the XPS 9570, but the kext companion [[https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/][guide]] includes
a good step-by-step tutorial on how to make DSDT edits with [[https://bitbucket.org/RehabMan/os-x-maciasl-patchmatic/downloads/][MaciASL]] if needed.
** Power Management (work in progress)
Note: There is some superfluous information on power management that applies only to older
architectures, and testing PM is a bit "heuristic". Will be updated when complete and tested working
100%.

Based on [[https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/][guide]] for laptop power management by RehabMan.

- Disable hibernation (suspend to disk or S4 sleep)
  macOS combines sleep and hibernation into one feature, where closing the lid initially sleeps the
  laptop, and eventually hibernates it. In any event, hibernation is not supported on hackintosh,
  and should be disabled/checked after updates.

  : sudo pmset -a hibernatemode 0
  : sudo rm -f /var/vm/sleepimage
  : sudo mkdir /var/vm/sleepimage # try to prevent update from re-enabling
  : sudo pmset -a standby 0
  : sudo pmset -a autopoweroff 0

- Testing Power Management

  Load [[file:tools/AppleIntelInfo.kext][AppleIntelInfo.kext]] (but don't install it):

  : sudo kextutil .../AppleIntelInfo.kext

  Then use the system for a few minutes, perform some work, let it idle, etc.
  Finally, copy results file:

  : sudo cp /tmp/AppleIntelInfo.dat .../AppleIntelInfo.txt

  "In addition, for Ivy Bridge and later (eg. Ivy, Haswell, Broadwell, Skylake, KabyLake, etc), you
  should run IORegistryExplorer and verify that X86PlatformPlugin is loading under the CPU0 node."

- Enabling Power Management

  config.plist/KernelAndKextPatches/KernelPm=true
*** Testing power management (WIP)
*** TODO Disable discrete NVIDIA GPU to save more power
** Windows compatibility
*** Real-time clock
macOS sets BIOS clock to UTC, but Windows sets clock to local time. The solution is to set Windows
to use UTC as well, with =regedit=:

  - regedit -> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation
  - create new DWORD (32-bit) 'RealTimeIsUniversal' with value '1'
** Known problems
*** Graphics acceleration becomes poor after display goes to sleep
*** Right-side USB port appears as an internal port, so devices attached to it can't be ejected
*** Hangs on boot with Apple logo intermittently
