#+STARTUP: indent
* Overview
This repository contains a sample configuration to run macOS Mojave (10.14) on a Dell XPS 9570.

This guide is currently a work in progress, since the XPS 9570 isn't perfectly supported yet. I will
update this guide as I test new fixes or updates. If you find any errors or problems, please let me
know. I'm hoping this will become the definitive guide for running macOS on the XPS 9570.

This repo and many pieces are based on the-darkvoid's [[https://github.com/the-darkvoid/XPS9360-macOS][XPS9360-macOS repo]], which is also a good guide
for other kexts/patches/solutions/etc.
** Tested configuration
- Dell XPS 9570
  - Intel i9-8950HK
  - 32GB RAM
  - Toshiba 2TB SSD
  - Goodix fingerprint reader
  - Wacom touchscreen
  - TODO: Touchpad manufacturer?
- Software environment
  - BIOS: 1.5.0
  - Dual-booting Windows 10
* Hardware
** Intel UHD 630 graphics
Intel graphics is supported by [[https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-kernel-panic-due-to-divide-by-zero.261687/][setting the maximum link rate in DPCD buffer]]. This may need to be
updated to support the HDMI port, because it may hard-code the link rate for this port instead of
using the value advertised by the connected display (TBD - haven't tried this yet). This fix also
allows the display to go to sleep without causing graphics to become choppy on wake-up.

To determine if Intel GPU acceleration is working, check: =About This Mac -> Intel UHD Graphics 630
1536 MB=. A value less than 1536MB indicates a problem (e.g. 7MB or 31MB are common).

Side note: Some threads discuss setting DVMT pre-alloc in the BIOS, which is not possible on most
laptops, including the XPS 9570. However, the default of 64MB DVMT is sufficient, so fortunately
nothing needs to be done here.
*** Enabling acceleration
- [[file:CLOVER/config.plist][config.plist]] changes (enable patch for 10.14 or 10.14.1, as needed)
  - Graphics/Inject/Intel=yes
  - Graphics/ig-platform-id=0x3e9b0000
  - KernelAndKextPatches/KextsToPatch/Item 1 (Maximum link rate 0x14 (HBR2) - works for 4K XPS 9570)
  - KernelAndKextPatches/KextsToPatch/Item 2 (Maximum link rate 0x0A (HBR) - needed for 1080p XPS 9570? TBD)
- Install [[https://github.com/acidanthera/WhateverGreen][WhateverGreen]] [[file:kexts/WhateverGreen.kext][kext]]
*** Enabling backlight control via slider in Sys. Prefs. -> Displays
Patched via kext and SSDT patch ([[https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightfixup-kext.218222/][discussion]]).  Can use pre-built [[https://bitbucket.org/RehabMan/applebacklightfixup/downloads/][kext and SSDT-PNLF.aml]], but the
.aml file should be the same as [[https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PNLF.dsl][SSDT-PNLF.dsl]] from [[https://github.com/RehabMan/OS-X-Clover-Laptop-Config][OS-X-Clover-Laptop-Config]].
- Include [[https://github.com/RehabMan/AppleBacklightFixup][AppleBacklightFixup]] [[file:kexts/AppleBacklightFixup.kext][kext]]
- Include [[file:CLOVER/ACPI/patched/SSDT-PNLF.aml][SSDT-PNLF.aml]] ([[file:CLOVER/ACPI/patched/SSDT-PNLF.dsl][SSDT-PNLF.dsl]])
*** Known issue: [[https://www.tonymacx86.com/threads/bug-black-screen-3-minutes-after-booting-coffeelake-uhd-630.261131/][Black/dark screen 3 minutes after booting with CoffeeLake UHD 630]]
Workaround: wait 3 minutes until a proper solution is found (TBD).

This problem seems to be surprisingly difficult to fix, partly because the people who are likely to
find a solution do not yet have UHD 630 hardware.
** PS/2 Keyboard
The internal keyboard is a PS/2 device, but macOS does not support PS/2. This can be implemented
with VoodooPS2Controller.

*** Installation
- Include [[https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller][VoodooPS2Controller]] [[file:kexts/VoodooPS2Controller.kext][kext]]
- Enabling brightness keys
  - Include [[file:CLOVER/ACPI/patched/SSDT-BRT6.aml][SSDT-BRT6.aml]] ([[file:CLOVER/ACPI/patched/SSDT-BRT6.dsl][SSDT-BRT6.dsl]])
  - [[file:CLOVER/config.plist][config.plist]] changes to rename BRT6 to BRTX in DSDT so we can replace it with our function
    - ACPI/DSDT/Patches/Item n
      - Key=Find, Type=Data, Value=<14204252 543602>
      - Key=Replace, Type=Data, Value=<14204252 545802>
- Include [[file:CLOVER/ACPI/patched/SSDT-PS2-Keymap.aml][SSDT-PS2-Keymap.aml]] ([[file:CLOVER/ACPI/patched/SSDT-PS2-Keymap.dsl][SSDT-PS2-Keymap.dsl]]) to remap keys (optional)
  - See list of [[https://wiki.osdev.org/PS/2_Keyboard][PS/2 scan codes (scan code set 1)]] for codes generated by keyboard, and [[file:/System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Headers/Events.h][ADB key codes]]
    for codes recognized by macOS.
*** Debugging key codes
- Install debug version of VoodooPS2Controller
- Log key codes captured
  #+BEGIN_SRC sh
  log stream | sed -n 's/.*\(ApplePS2Keyboard: sending key\)/\1/p'
  #+END_SRC
*** Known problems/caveats
- Can cause reboot on startup (intermittent)
- Can cause brightness controls to work immediately on boot, possibly indicating OOB memory access (intermittent)
- Keyboard options like modifier key settings cause an erratic/disabled keyboard
  For key remapping, see SSDT-PS2-Keymap.dsl above. Key repeat speed and delay are ok to change.
- Can't wake up from sleep with internal keyboard
- Enables poor quality touchpad by default
** Battery status
- Install [[https://github.com/RehabMan/OS-X-ACPI-Battery-Driver][ACPIBatteryManager]] [[file:kexts/ACPIBatteryManager.kext][kext]]

Only the ACPIBatteryManager kext is required on the XPS 9570, but the kext companion [[https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/][guide]] includes
a good step-by-step tutorial on how to make DSDT edits with [[https://bitbucket.org/RehabMan/os-x-maciasl-patchmatic/downloads/][MaciASL]] if needed.
** Power management (work in progress)
Note: There is some superfluous information on power management that applies only to older
architectures, and testing PM is a bit "heuristic". Will be updated when complete and tested working
100%.

Based on [[https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/][guide]] for laptop power management by RehabMan.

- Disable hibernation (suspend to disk or S4 sleep)
  macOS combines sleep and hibernation into one feature, where closing the lid initially sleeps the
  laptop, and eventually hibernates it. In any event, hibernation is not supported on hackintosh,
  and should be disabled/checked after updates.

#+BEGIN_SRC sh
sudo pmset -a hibernatemode 0
sudo rm -f /var/vm/sleepimage
sudo mkdir /var/vm/sleepimage # try to prevent update from re-enabling
sudo pmset -a standby 0
sudo pmset -a autopoweroff 0
#+END_SRC
- Testing Power Management
  Load [[file:tools/AppleIntelInfo.kext][AppleIntelInfo.kext]] (but don't install it):

#+BEGIN_SRC sh
sudo kextutil .../AppleIntelInfo.kext
#+END_SRC

Then use the system for a few minutes, perform some work, let it idle, etc.
Finally, copy results file:

#+BEGIN_SRC sh
sudo cp /tmp/AppleIntelInfo.dat .../AppleIntelInfo.txt
#+END_SRC

"In addition, for Ivy Bridge and later (eg. Ivy, Haswell, Broadwell, Skylake, KabyLake, etc), you
should run IORegistryExplorer and verify that X86PlatformPlugin is loading under the CPU0 node."
- Enabling Power Management
  config.plist/KernelAndKextPatches/KernelPm=true
*** Testing power management (WIP)
Use [[https://software.intel.com/en-us/articles/intel-power-gadget-20][Intel Power Gadget]] to graph CPU power/frequency/temp over time.
*** TODO Disable discrete NVIDIA GPU to save more power
** Audio
Audio does not work by default.

One symptom of broken audio drivers is constant CPU activity in a =kernel_task= process.

The recommended audio patch is [[https://github.com/acidanthera/AppleALC][AppleALC]].
** USB
The XPS 9570 DSDT table has a few incorrect USB properties, for example the right side type A port
is marked as being internal, so an attached disk can't be easily ejected. The correct properties are
injected via USBInjectAll and in [[file:CLOVER/ACPI/patched/SSDT-UIAC.dsl][SSDT-UIAC.dsl]].

Based on [[https://www.tonymacx86.com/threads/guide-10-11-usb-changes-and-solutions.173616/][USB guide]] and [[https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/][companion guide.]]

USB config reported by DSDT (connectable ports only):
| Port | Visible | Type        |
|------+---------+-------------|
| HS01 | Yes     | Proprietary |
| HS02 | Yes     | Type A      |
| HS04 | No      | Proprietary |
| HS05 | Yes     | Proprietary |
| HS07 | No      | Proprietary |
| HS09 | No      | Proprietary |
| HS12 | No      | Proprietary |
| SS01 | Yes     | Proprietary |
| SS02 | Yes     | Proprietary |

Actual hwardware config:
| Port      | Type        | User Visible* | Description                                |
|-----------+-------------+---------------+--------------------------------------------|
| HS01/SS01 | Type A      | Yes           | Right side                                 |
| HS02/SS02 | Type A      | Yes           | Left side                                  |
| HS04      | Proprietary | No            | Bluetooth                                  |
| HS05      | Type C      | Yes           | Left side                                  |
| HS07      | Proprietary | No            | Goodix fingerprint reader                  |
| HS09      | Proprietary | No            | No longer used; touchscreen on prior model |
| HS12      | Proprietary | No            | Webcam                                     |

(*) "Set if the device connection point can be seen by the user without disassembly" according to
ACPI 6.2 A, 6.1.8, _PLD (Physical Location of Device)
*** Implementing USB port fixes and removing unused ports
- Include [[https://github.com/RehabMan/OS-X-USB-Inject-All][USBInjectAll]] [[file:kexts/USBInjectAll.kext][kext]]
- Include [[file:CLOVER/ACPI/patched/SSDT-UIAC.aml][SSDT-UIAC.aml]] ([[file:CLOVER/ACPI/patched/SSDT-UIAC.dsl][SSDT-UIAC.dsl]]) - based on [[https://github.com/RehabMan/OS-X-USB-Inject-All/blob/master/SSDT-UIAC-ALL.dsl][SSDT-UIAC-ALL.dsl]] and customized for XPS 9570
*** Known issue: left side type C port only works in HS mode, not SS
Will likely work when USB type C and/or Thunderbolt fixes are added.
*** Unintended side effect: *intermittently* causes screen brightness to work without 3 min. delay
This occurs without a port limit patch, without SSDT-UIAC.aml, and boot flags "-uia_exclude_hs uia_include=HS04".
** Windows compatibility
*** Real-time clock
macOS sets BIOS clock to UTC, but Windows sets clock to local time. The solution is to set Windows
to use UTC as well, with =regedit=:

- regedit -> =HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation=
- create new DWORD (32-bit) =RealTimeIsUniversal= with value '1'
** Known problems/caveats
- Temporary hang whenever Touch ID is requested (TODO: disable Touch ID, look into fingerprint sensor)
- Internal keyboard behaves strangely with [[https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller][OS-X-Voodoo-PS2-Controller]], poor touchpad support
- iMessage does not work by default (haven't tried)
- Drive encryption is disabled (not tested)
  (note to self: see Clover installer for "FileVault 2" UEFI drivers)
- Use Goodix fingerprint reader for Touch ID?
- WiFi not working with built-in Killer card
- Bluetooth can't be disabled, and doesn't wake system from sleep
- Thunderbolt not working (haven't tried)
- Suspend and resume a little wonky
- SD card reader not present
- +Right-side USB port appears as an internal port, so devices attached to it can't be ejected+
- +Hang on boot with Apple logo intermittently+
- +Graphics acceleration becomes poor after display goes to sleep+
- +Constant CPU activity in kernel_task process+
  (Symptom of broken audio patch - either fix or remove)
* ACPI DSDT/SSDT patching
Most of the ACPI patching info is based on the [[https://www.tonymacx86.com/threads/guide-patching-laptop-dsdt-ssdts.152573/][laptop DSDT/SSDT guide]] and [[https://www.tonymacx86.com/threads/guide-using-clover-to-hotpatch-acpi.200137/][hotpatching guide]].

Many ACPI patches depend on starting out with a working set of ACPI tables (accomplished via
patching if needed), so it's useful to test if this is the case and fix any errors before attempting
further changes.

To do this, we can look through the macOS boot logs for ACPI errors, dump the unmodified ACPI
tables, and dump the ACPI tables as modified by Clover. Making changes as needed, rebooting, and
re-inspecting system logs, we can iterate until there are no more ACPI problems as seen by macOS.

Note: this process wasn't clear to me from reading the patching guides initially, but it may not be
the best way to do it - caveat emptor.

1. Inspect system logs for errors
   Immediately after bootup, dump system log for the last 10 minutes (adjust as needed):
   =log show --predicate 'process == "kernel"' --style syslog --source --debug --last 10m > sys_log.txt=
   Then search =sys_log.txt= for "ACPI Error" or "ACPI Exception".
2. Dump unmodified ACPI tables
   Press F4 on Clover boot screen (no output will show), then mount EFI partition and look for
   ACPI tables in =CLOVER/ACPI/origin=.
3. Check unmodified tables for errors with iasl
   Disassembling all tables from a single namespace with the =-da= option should yield no errors:
   =iasl -da -dl DSDT.aml SSDT-*.aml=
   Although, some duplicate definitions with the error AE_ALREADY_EXISTS may not be a problem (TBD).
   If an error occurs, check the file =DSDT.dsl= for possible error output.
4. Check modified tables as injected by Clover with patchmatic and iasl
   #+BEGIN_SRC sh
   patchmatic -extract
   iasl -da -dl DSDT.aml SSDT-*.aml
   #+END_SRC
   Again, this should yield no errors. If a duplicate definition is found with AE_ALREADY_EXISTS,
   try disassembling the tables without the =-da= option:
   =iasl -dl DSDT.aml SSDT-*.aml=
   If this still fails, there is likely a problem that needs to be fixed via Clover patching first.
* Installation and system updates
** Installation from scratch
*** Preparing the XPS 9570
This setup dual-boots Windows 10, which is nice to have for games, since we can actually use the
NVIDIA GTX 1050, unlike in macOS.

Begin with the default Windows 10 installation (or install Windows 10 if using a new drive).

- Update BIOS and other firmware using Dell SupportAssist in Windows
- Toshiba SSD only
  - Update [[https://www.dell.com/support/home/us/en/04/product-support/product/xps-15-9570-laptop/drivers][Toshiba SSD firmware]] (search for "toshiba")
    Needed to fix 4k sector bug. Dell SupportAssist does not do this automatically!
  - Set SSD to [[https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/4k_sector.md][use 4k sectors]] - this will WIPE the drive!
- Enable Intel SpeedShift in BIOS
- TODO: add more steps from original notes.org
*** Creating USB installation media (see [[https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/][guide]] for more details)
- Download macOS install from App Store
- Format USB drive and write installer to drive (assuming drive is =/dev/disk100=)
  #+BEGIN_SRC sh
  diskutil partitionDisk /dev/disk100 1 GPT HFS+J "install_osx" R
  sudo "/Applications/Install macOS Mojave.app/Contents/Resources/createinstallmedia" --volume  /Volumes/install_osx --nointeraction
  diskutil rename "Install macOS Mojave" install_osx
  #+END_SRC
- Install Clover on USB drive
  - Using RehabMan's fork of Clover: [[https://github.com/RehabMan/Clover][source]], [[https://bitbucket.org/RehabMan/clover/downloads/][binaries]]
  - Run installer
    - 'Change Install Location' -> Select =install_osx= volume
    - 'Customize', then apply the following _changes_
      - [X] Clover for UEFI booting only
      - [X] UEFI Drivers -> VBoxHfs-64
- TODO: This isn't enough to boot the installer - will need to provide config.plist. Re-visit when documenting full installation process.
  Installing updates is possible when injecting Intel graphics, with invalid platform id, e.g. 0x12345678, and disabling kext patches.
  Perhaps it makes sense to have a special macOS install CLOVER folder, that disables any brightness 'fixes' that cause the display to be dimmed. TBD.
* Versions
- Clover: v2.4k r4701 RM-4963
* Miscellaneous Notes
** Installing kexts
Kexts should be installed in =/Library/Extensions=.

Installation:
#+BEGIN_SRC sh
sudo cp -r <mydriver.kext> /Library/Extensions
sudo chown -R root:wheel /Library/Extensions/<mydriver.kext>
sudo kextcache -i / # update kext cache
#+END_SRC

*Be sure to check output for errors!*

Every custom kext should be listed with the line =Kext with invalid signatured (-67062) allowed=
** Kext patching
Kexts can be patched on boot by Clover (see =KernelAndKextPatches/KextsToPatch= section in
[[file:CLOVER/config.plist][config.plist]]), but Clover has some limitations, e.g. it can only patch kexts that are in the kext
cache. More complex cases can be handled by [[https://github.com/acidanthera/Lilu][Lilu]], used for "arbitrary kext and process patching",
which is itself installed as a [[file:kexts/Lilu.kext][kext]]. Excellent [[https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/][guide]] to using Lilu and commonly used plugins.
** ACPI debugging
The [[https://github.com/RehabMan/OS-X-ACPI-Debug][OS-X-ACPI-Debug]] repo allows for "debug tracing from ACPI code (DSDT) to system.log".
Not currently installed and not tested, but should be useful if ACPI  problems come up.
** Links to tonymacx86.com guides, etc
*** [[https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/][Laptop Frequent Questions]]
Long, thorough guide. Good to refer back to for specific issues.
