* Overview
This repository contains a sample configuration to run macOS Mojave (10.14) on a Dell XPS 9570.

This guide is currently a work in progress, since the XPS 9570 isn't perfectly supported yet. I will
update this guide as I test new fixes or updates. If you find any errors or problems, please let me
know. I'm hoping this will become the definitive guide for running macOS on the XPS 9570.
** Tested configuration
- Dell XPS 9570
  - Intel i9-8950HK
  - 32GB RAM
  - Toshiba 2TB SSD
  - BIOS: 1.5.0
- Software environment
  - Dual-booting Windows 10
* Hardware
** Intel UHD 630 Graphics
Intel graphics is supported by [[https://www.tonymacx86.com/threads/fix-coffee-lake-intel-uhd-graphics-630-on-macos-mojave-kernel-panic-due-to-divide-by-zero.261687/][setting the maximum link rate in DPCD buffer]]. This may need to be
updated to support the HDMI port, because it may hard-code the link rate for this port instead of
using the value advertised by the connected display (TBD - haven't tried this yet). This fix also
allows the display to go to sleep without causing graphics to become choppy on wake-up.

To determine if Intel GPU acceleration is working, check: =About This Mac -> Intel UHD Graphics 630
1536 MB=. A value less than 1536MB indicates a problem (e.g. 7MB or 31MB are common).

Side note: Some threads discuss setting DVMT pre-alloc in the BIOS, which is not possible on most
laptops, including the XPS 9570. However, the default of 64MB DVMT is sufficient, so fortunately
nothing needs to be done here.
*** Enabling acceleration
- [[file:CLOVER/config.plist][config.plist]] changes (enable patch for 10.14 or 10.14.1, as needed)
  - Graphics/Inject/Intel=yes
  - Graphics/ig-platform-id=0x3e9b0000
  - KernelAndKextPatches/KextsToPatch/Item 1 (Maximum link rate 0x14 (HBR2) - works for 4K XPS 9570)
  - KernelAndKextPatches/KextsToPatch/Item 2 (Maximum link rate 0x0A (HBR) - needed for 1080p XPS 9570? TBD)
- Install [[https://github.com/acidanthera/WhateverGreen][WhateverGreen]] [[file:kexts/WhateverGreen.kext][kext]]
*** Enabling backlight control via slider in =Sys Prefs -> Displays=
Patched via kext and SSDT patch ([[https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightfixup-kext.218222/][discussion]]).  Can use pre-built [[https://bitbucket.org/RehabMan/applebacklightfixup/downloads/][kext and SSDT-PNLF.aml]], but the
 .aml file should be the same as [[https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/hotpatch/SSDT-PNLF.dsl][SSDT-PNLF.dsl]] from [[https://github.com/RehabMan/OS-X-Clover-Laptop-Config][OS-X-Clover-Laptop-Config]].
- Include [[https://github.com/RehabMan/AppleBacklightFixup][AppleBacklightFixup]] [[file:kexts/AppleBacklightFixup.kext][kext]]
- Include [[file:CLOVER/ACPI/patched/SSDT-PNLF.aml][SSDT-PNLF.aml]] ([[file:CLOVER/ACPI/patched/SSDT-PNLF.dsl][SSDT-PNLF.dsl]])
*** Known issue: [[https://www.tonymacx86.com/threads/bug-black-screen-3-minutes-after-booting-coffeelake-uhd-630.261131/][Black/dark screen 3 minutes after booting with CoffeeLake UHD 630]]
Workaround: wait 3 minutes until a proper solution is found (TBD).

This problem seems to be surprisingly difficult to fix, partly because the people who are likely to
find a solution do not yet have UHD 630 hardware.
** Battery Status
- Install [[https://github.com/RehabMan/OS-X-ACPI-Battery-Driver][ACPIBatteryManager]] [[file:kexts/ACPIBatteryManager.kext][kext]]

Only the ACPIBatteryManager kext is required on the XPS 9570, but the kext companion [[https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/][guide]] includes
a good step-by-step tutorial on how to make DSDT edits with [[https://bitbucket.org/RehabMan/os-x-maciasl-patchmatic/downloads/][MaciASL]] if needed.
** Power Management (work in progress)
Note: There is some superfluous information on power management that applies only to older
architectures, and testing PM is a bit "heuristic". Will be updated when complete and tested working
100%.

Based on [[https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/][guide]] for laptop power management by RehabMan.

- Disable hibernation (suspend to disk or S4 sleep)
  macOS combines sleep and hibernation into one feature, where closing the lid initially sleeps the
  laptop, and eventually hibernates it. In any event, hibernation is not supported on hackintosh,
  and should be disabled/checked after updates.

#+BEGIN_SRC sh
  sudo pmset -a hibernatemode 0
  sudo rm -f /var/vm/sleepimage
  sudo mkdir /var/vm/sleepimage # try to prevent update from re-enabling
  sudo pmset -a standby 0
  sudo pmset -a autopoweroff 0
#+END_SRC
- Testing Power Management

  Load [[file:tools/AppleIntelInfo.kext][AppleIntelInfo.kext]] (but don't install it):

#+BEGIN_SRC sh
  sudo kextutil .../AppleIntelInfo.kext
#+END_SRC

  Then use the system for a few minutes, perform some work, let it idle, etc.
  Finally, copy results file:

#+BEGIN_SRC sh
  sudo cp /tmp/AppleIntelInfo.dat .../AppleIntelInfo.txt
#+END_SRC

  "In addition, for Ivy Bridge and later (eg. Ivy, Haswell, Broadwell, Skylake, KabyLake, etc), you
  should run IORegistryExplorer and verify that X86PlatformPlugin is loading under the CPU0 node."

- Enabling Power Management

  config.plist/KernelAndKextPatches/KernelPm=true
*** Testing power management (WIP)
*** TODO Disable discrete NVIDIA GPU to save more power
** Windows compatibility
*** Real-time clock
macOS sets BIOS clock to UTC, but Windows sets clock to local time. The solution is to set Windows
to use UTC as well, with =regedit=:

  - regedit -> =HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\TimeZoneInformation=
  - create new DWORD (32-bit) =RealTimeIsUniversal= with value '1'
** Known problems/caveats
   - Right-side USB port appears as an internal port, so devices attached to it can't be ejected
   - Internal keyboard behaves strangely with [[https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller][OS-X-Voodoo-PS2-Controller]], poor touchpad support
   - Constant CPU activity in =kernel_task=
   - iMessage does not work
   - Drive encryption is disabled (not tested)
   - Hangs on boot with Apple logo intermittently (TBD: may be fixed by new link rate patch, still testing)
     (note to self: see Clover installer for "FileVault 2" UEFI drivers)
   - +Graphics acceleration becomes poor after display goes to sleep+
     (Fixed by new the link rate in the graphics section)
* Installation and system updates
** Clover boot manager

   Clover install is based on RehabMan's laptop [[https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/][installation guide]].

   For now, we're using RehabMan's fork of Clover ([[https://github.com/RehabMan/Clover][source]], [[https://bitbucket.org/RehabMan/clover/downloads/][binaries]]).

   link? version? new features?
** Updating 10.14 -> 10.14.1 (work in progress)
(Note to self: see [[https://github.com/Xigtun/xps-9570-mojave][xps-9750-mojave]] repo)
* Miscellaneous Notes
** Installing kexts
Kexts should be installed in =/Library/Extensions=.

Installation:
#+BEGIN_SRC sh
  sudo cp -r <mydriver.kext> /Library/Extensions
  sudo kextcache -i / # update kext cache
#+END_SRC

*Be sure to check output for errors!*

Common problems are wrong permissions or file ownership.
** Kext patching
Kexts can be patched on boot by Clover (see =KernelAndKextPatches/KextsToPatch= section in
[[file:CLOVER/config.plist][config.plist]]), but Clover has some limitations, e.g. it can only patch kexts that are in the kext
cache. More complex cases can be handled by [[https://github.com/acidanthera/Lilu][Lilu]], used for "arbitrary kext and process patching",
which is itself installed as a [[file:kexts/Lilu.kext][kext]].
** ACPI debugging
The [[https://github.com/RehabMan/OS-X-ACPI-Debug][OS-X-ACPI-Debug]] repo allows for "debug tracing from ACPI code (DSDT) to system.log".
Not currently installed and not tested, but should be useful if ACPI  problems come up.
