#+STARTUP: indent
* Display/Graphics
** WhateverGreen.kext (1.3.1)
https://github.com/acidanthera/WhateverGreen
Lilu plugin providing patches for GPUs on macOS.
* Wi-Fi/Bluetooth
See readme for more info on Wi-Fi and Bluetooth - different options may be needed depending on the
Broadcom card used.
** AirportBrcmFixup.kext (2.0.3)
https://github.com/acidanthera/AirportBrcmFixup
Fixes WiFi card to appear as Airport Extreme, and makes the card appear to be native.
** BrcmBluetoothInjector.kext/BrcmFirmwareRepo.kext/BrcmPatchRAM3.kext (V2.3.0d3)
https://github.com/acidanthera/BrcmPatchRAM
Enables Bluetooth on supported Broadcom cards.
Binary [[https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/?do=findComment&comment=2693219][built by Mieze]].
* AppleALC (1.4.0)
https://github.com/acidanthera/AppleALC
Enables audio for Realtek ALC298 (ALC3266 according to Dell).
* NoTouchID (1.0.2)
https://github.com/al3xtjames/NoTouchID
Disables support for Touch ID, which is useful to prevent lags on auth dialogs. This occurs on
SMBIOS versions where Touch ID is expected, e.g. MacBookPro15,1 that we're using for the XPS 9570.
* USBInjectAll (2018-1108)
https://github.com/RehabMan/OS-X-USB-Inject-All
Inject custom USB port properties to work around buggy ACPI tables.
* VoodooPS2Controller (2018-1008)
https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller
Support internal PS/2 keyboard.
* VoodooI2C/VoodooI2CHID (2.2)
https://github.com/alexandred/VoodooI2C
Support touchpad and touchscreen as I2C devices.
* Lilu (1.3.8)
https://github.com/acidanthera/Lilu
An open source kernel extension bringing a platform for arbitrary kext, library, and program
patching throughout the macOS. Required by WhateverGreen and other kexts.
* VirtualSMC/SMCBatteryManager/SMCLightSensor/SMCProcessor/SMCSuperIO (1.0.7)
https://github.com/acidanthera/VirtualSMC
Apple SMC emulator. Required to boot macOS on a hackintosh, since PCs
do not have Apple SMC hardware.
* Notes
All kexts are release versions, if both debug and release are provided.

Kexts should also be installed to /Library/Extensions.
