#+STARTUP: indent
* AppleIntelInfo.kext (2.9)
https://github.com/Piker-Alpha/AppleIntelInfo
Record CPU p-state info to test power management - loaded manually for debugging only.
Manually compiled with Xcode. Used with power management guide:
https://www.tonymacx86.com/threads/guide-native-power-management-for-laptops.175801/
* BT-LinkkeySync.py (modified to work with Mojave)
https://github.com/digitalbirdo/BT-LinkkeySync
Export Bluetooth 128 bit link keys from macOS so that Bluetooth
devices work when booting macOS or Windows without re-pairing
constantly.
* Clover (v2.4k_r4928)
https://github.com/Dids/clover-builder
Clover EFI boot manager. Required to boot macOS.
* IORegistryExplorer (2.1)
https://www.tonymacx86.com/audio/58368-guide-how-make-copy-ioreg.html
Used to view device tree and debug many harware and ACPI issues.
Should use v2.1, not a later version, which has new and un-fixed bugs.
* MaciASL.app (2018-0507)
https://github.com/RehabMan/OS-X-MaciASL-patchmatic
ACPI editor/compiler for DSDT patching.
* iasl (2018-05-07, iasl.zip, tool reported version: 20180427(RM))
https://bitbucket.org/RehabMan/acpica/downloads/
Intel ACPI ASL+ Optimizing Compiler/Disassembler
* patchmatic (2018-0507)
https://github.com/RehabMan/OS-X-MaciASL-patchmatic
ACPI utility to read DSDT/SSDT as patched by Clover.
